#!/usr/bin/env python
"""numbers_coverage.tex from results/analysis/coverage.json and erasure.json (both post hoc analyses).

Macros: entry-level coverage curve (lookup accuracy by c, the number of times the exact (remainder, digit)
entry appeared in the cell's training traces), div7 vs div13 at n = 180, arm D lookup vs local accuracy,
within-cell rank correlation, and item-level keep rates of A, B and S on base-solved items at 3B and 7B.
usage: python paper/exp/make_coverage_numbers.py
"""
from __future__ import annotations

import json
import math
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
PAPER = os.path.join(ROOT, "paper")
BINS = ["0", "1", "2", "3-4", "5-8", "9-16", "17-32", "33-64"]
NAMES = ["zero", "one", "two", "threefour", "fiveeight", "ninesixteen", "seventeen", "thirtythree"]
M = {}


def pct(x):
    return f"{100 * x:.1f}"


def fmt_p(p):
    if p >= 0.01:
        return f"{p:.2f}"
    e = int(math.floor(math.log10(max(p, 1e-300))))
    m = int(round(p / 10 ** e))
    if m == 10:
        m, e = 1, e + 1
    return f"{m}\\times10^{{{e}}}"


def curve(d, prefix):
    for b, name in zip(BINS, NAMES):
        if b in d:
            M[prefix + name] = pct(d[b]["acc"])
            M[prefix + name + "N"] = str(d[b]["n_steps"])
        else:
            M[prefix + name] = "--"
            M[prefix + name + "N"] = "0"


def pooled(d):
    n = sum(v["n_steps"] for v in d.values())
    k = sum(v["n_correct"] for v in d.values())
    return k / n if n else float("nan")


def main():
    cov = json.load(open(os.path.join(ROOT, "results", "analysis", "coverage.json"), encoding="utf-8"))
    lk = cov["results"]["lookup"]
    lc = cov["results"]["local"]
    M["covSteps"] = f"{lk['n_steps_primary']:,}"
    M["covAccPooled"] = pct(lk["acc_primary"]["acc"])
    curve(lk["curve_by_trivial"]["nontrivial"], "covNT")
    curve(lk["curve_n180_4digit_by_task"]["div7"], "covDseven")
    curve(lk["curve_n180_4digit_by_task"]["div13"], "covDthirteen")
    M["covDlookup"] = pct(pooled(lk["curve_secondary_roles"]["arm_D"]))
    M["covDlocal"] = pct(pooled(lc["curve_secondary_roles"]["arm_D"]))
    sp = lk["within_cell_spearman"]["summary"]
    M["covRhoCells"] = str(sp["n_cells"])
    M["covRhoPos"] = str(sp["n_positive"])
    M["covRhoMedian"] = f"{sp['median_rho']:.2f}"
    M["covRhoP"] = fmt_p(sp["wilcoxon_p_two_sided"])
    th = lk["threshold_nontrivial"]
    M["covCstar"] = str(th["c_star"])
    M["covCstarAcc"] = pct(th["acc"])

    er = json.load(open(os.path.join(ROOT, "results", "analysis", "erasure.json"), encoding="utf-8"))
    want = {("Qwen2.5-3B-Instruct", "div7", "A", 180): "erThreeBdivsevenAkeep",
            ("Qwen2.5-7B-Instruct", "div7", "A", 180): "erSevenBdivsevenAkeep",
            ("Qwen2.5-3B-Instruct", "div7", "S", 180): "erThreeBdivsevenSkeep",
            ("Qwen2.5-7B-Instruct", "div7", "S", 180): "erSevenBdivsevenSkeep",
            ("Qwen2.5-3B-Instruct", "div7", "B", 180): "erThreeBdivsevenBkeep",
            ("Qwen2.5-7B-Instruct", "div7", "B", 180): "erSevenBdivsevenBkeep",
            ("Qwen2.5-3B-Instruct", "div13", "A", 180): "erThreeBdivthirteenAkeep",
            ("Qwen2.5-7B-Instruct", "div13", "A", 180): "erSevenBdivthirteenAkeep"}
    for c in er["cells"]:
        key = (c["model"], c["cell"], c["arm"], c["n"])
        if key in want and c.get("ref") == "plain" and c.get("eval_task") == c["cell"]:
            M[want[key]] = pct(c["keep_mean"])
            M[want[key] + "Seeds"] = str(len(c["seeds"]))
    for name in want.values():
        M.setdefault(name, "--")
        M.setdefault(name + "Seeds", "0")

    out = os.path.join(PAPER, "numbers_coverage.tex")
    with open(out, "w", encoding="utf-8") as f:
        f.write("% generated by paper/exp/make_coverage_numbers.py; do not edit\n")
        for k, v in M.items():
            f.write("\\newcommand{\\%s}{%s}\n" % (k, v))
    print("wrote", out, len(M), "macros")
    for k in ("covSteps", "covNTzero", "covNTthirtythree", "covDlookup", "covDlocal", "covRhoPos", "covRhoCells",
              "erThreeBdivsevenAkeep", "erSevenBdivsevenAkeep", "erThreeBdivsevenSkeep", "erSevenBdivsevenSkeep"):
        print(f"  {k} = {M[k]}")


if __name__ == "__main__":
    main()
